FROM coffeateam/coffea-casa:0.4.0

RUN pip install --ignore-installed --no-cache-dir \
    git+git://github.com/mat-adamec/coffea-casa.git@master#egg=coffea_casa
    
COPY prepare-env.sh /usr/local/bin/